routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});
    

Route::group(['prefix' => '/admin', 'namespace' => 'Backend'], function() {
    
    // Home / Dashboard
    Route::get('/', function(){
        
        return redirect()->route('autos.index');
        
    })->name('admin.index');
    
    
    // Autos
    Route::resource('/autos', 'AutoController');
    
    // Config -> Smtp
    Route::get('/smtp', 'SmtpController@edit')->name('smtp.edit');
    Route::put('/smtp', 'SmtpController@update')->name('smtp.update');
    
    // Config -> Agência
    Route::get('/agencia', 'AgencyController@edit')->name('agency.edit');
    Route::put('/agencia', 'AgencyController@update')->name('agency.update');
    
    // Config -> Usuários
    Route::resource('/users', 'UserController')->except('show');
    
    // Redes Sociais
    Route::get('/socials', 'SocialController@edit')->name('social.edit');
    Route::put('/socials', 'SocialController@update')->name('social.update');
    
    // Depoimentos
    Route::resource('/testemonials', 'TestemonialController')->except('show');
    
    // Serviços
    Route::resource('/services', 'ServiceController')->except('show');
    
    // Slides
    Route::resource('/slides', 'SlideController')->except('show');
    
    // Parceiros
    Route::resource('/partners', 'PartnerController')->except('show');
    
    // Cores
    Route::resource('/colors', 'ColorController')->except('show');
    
    // Câmbios
    Route::resource('/gearboxes', 'GearboxController')->except('show');
    
    // Marcas
    Route::resource('/brands', 'BrandController')->except('show');
    Route::get('/brands/{id}/models', 'BrandController@models')->name('brands.models');
    
    // Modelos
    Route::resource('/models', 'ModelController')->except('show');
    Route::get('/models/{id}/versions', 'ModelController@versions')->name('models.versions');
    
    // Versões
    Route::resource('/versions', 'VersionController')->except('show');
    
    // Grupos de Opcionais
    Route::get('/groups/{id}/optionals', 'GroupController@optionals')->name('groups.optionals');
    Route::resource('/groups', 'GroupController')->except('show');
    
    // Opcionais
    Route::resource('/optionals', 'OptionalController')->except('show');
});
        

app/Http/Controllers/Backend/AgencyController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\Upload;
use App\Http\Controllers\Controller;
use App\Models\Agency;
use Illuminate\Http\Request;

class AgencyController extends Controller
{
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        $agency = Agency::first();
        
        return view('backend.agency.form', compact('agency'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agency $agency)
    {
        $request->validate([
            'name' => 'required|min:10|max:100',
            'phone' => 'required|min:13|max:15',
            'phone2' => 'nullable|min:13|max:15',
            'phone3' => 'nullable|min:13|max:15',
            'address' => 'required|min:5|max:200',
            'business_hours' => 'required|min:5|max:60',
            'title' => 'required|min:5|max:60',
            'description' => 'required|min:10|max:1000',
            'seo_description' => 'min:10|max:100',
            'seo_keys' => 'min:5|max:30',
            'logotipo' => 'mimes:jpeg,bmp,png|dimensions:max_width=210,max_height=40',
        ]);
        
        // recupera o primeiro registro da tabela agencies, pois sempre haverá apenas 1 único registro
        $agency = Agency::first();
        
        // recupera o caminho completo da imagem antiga salva no BD para exclusão
        $pathOldPhoto = public_path() . '/uploads/agency/' . $agency->photo;
        
        // executa o upload e retorna o resultado. Se retorna o nome do arquivo, é porque o upload foi bem-sucedido
        $novoNomeArquivo = Upload::execute('logotipo', 'agency', $pathOldPhoto);
        
        // se o resultado retornar false, é porque houve algum erro ao se fazer o upload
        if ($novoNomeArquivo === false) {
            return redirect()->back()->with('error', 'Falha ao fazer upload da foto!')->withInput();
        }
        
        // recupera os dados da requisição e adiciona o nome gerado no upload da imagem ao atributo photo
        $dadosRequisicao = $request->all();
        $dadosRequisicao['photo'] = $novoNomeArquivo;
        
        if ($agency->update($dadosRequisicao))
        {
            return redirect()->route('agency.edit')->with('success', 'Agência atualizada com sucesso!');
        }
        
        return redirect()->back()->with('error', 'Falha ao atualizar Agência!')->withInput();
    }
}

app/Http/Controllers/Backend/AutoController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Auto;
use App\Services\AutoService;
use Illuminate\Http\Request;
use App\Http\Requests\AutoFormRequest;

class AutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$autos = AutoService::findAll();

        $autos = Auto::join('brands', 'autos.brand_id', '=', 'brands.id')
                        ->join('models', 'models.id', '=', 'autos.model_id')
                        ->join('versions', 'versions.id', '=', 'autos.version_id')
                        ->select('autos.id as auto_id', 'models.name as model_name', 'versions.name as version_name',
                            'brands.name as brand_name', 'autos.photo', 'autos.is_featured')
                        ->paginate(config('constants.NUM_RECORDS_PER_PAGE'));
        
        return view('backend.auto.index', compact('autos', 'brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = AutoService::getBrands();
        $models = AutoService::getModels();
        $years = AutoService::getYears();
        $gearboxes = AutoService::getGearboxes();
        $colors = AutoService::getColors();
        $fuels = AutoService::getFuels();
        $bodyworks = AutoService::getBodyworks();
        $documentations = AutoService::getDocumentations();
        $needs = AutoService::getNeeds();
        $plates = AutoService::getPlates();
        $ports = AutoService::getPorts();
        $negotiableTypes = AutoService::getNegotiableTypes();
        $optionalsGroup = AutoService::getOptionalsGroup();
        $optionals = AutoService::getOptionals();
        $versions = AutoService::getVersions();


        return view('backend.auto.form', compact('brands', 'models', 'years', 'gearboxes', 'colors', 'fuels',
            'bodyworks', 'documentations', 'needs', 'plates', 'ports', 'negotiableTypes', 'optionals',
            'optionalsGroup', 'versions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Auto $auto)
    {
        //$request->replace(['km' => intval(str_replace('.', '', $request->input('km')))]);
        //dd($request->all());
        $request->replace(['km' => intval(str_replace('.', '', $request->input('km')))]);
        $request->replace(['price' => floatval(str_replace('R$ ', '', str_replace('.', '', str_replace(',', '.', $request->input('price')))))]);

        $request->validate(Auto::validationRules());

        if ($auto->create($request->all())) {

            // salvar os opcionais na tabela de auto_optional

            return redirect()->route('autos.index')->with('success', 'Auto <b>' . '' . '</b> criado com sucesso!');
        }

        return redirect()->back()->with('error', 'Falha ao criar auto!')->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Auto  $auto
     * @return \Illuminate\Http\Response
     */
    public function show(Auto $auto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Auto  $auto
     * @return \Illuminate\Http\Response
     */
    public function edit(Auto $auto)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Auto  $auto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Auto $auto)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Auto  $auto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Auto $auto)
    {
        //
    }
}

app/Http/Controllers/Backend/AutoOptionalController.php
<?php

namespace App\Http\Controllers;

use App\Models\AutoOptional;
use Illuminate\Http\Request;

class AutoOptionalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\AutoOptional  $autoOptional
     * @return \Illuminate\Http\Response
     */
    public function show(AutoOptional $autoOptional)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\AutoOptional  $autoOptional
     * @return \Illuminate\Http\Response
     */
    public function edit(AutoOptional $autoOptional)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\AutoOptional  $autoOptional
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AutoOptional $autoOptional)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\AutoOptional  $autoOptional
     * @return \Illuminate\Http\Response
     */
    public function destroy(AutoOptional $autoOptional)
    {
        //
    }
}

app/Http/Controllers/Backend/BodyworkController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bodywork;
use Illuminate\Http\Request;

class BodyworkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bodywork  $bodywork
     * @return \Illuminate\Http\Response
     */
    public function show(Bodywork $bodywork)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bodywork  $bodywork
     * @return \Illuminate\Http\Response
     */
    public function edit(Bodywork $bodywork)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bodywork  $bodywork
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bodywork $bodywork)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bodywork  $bodywork
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bodywork $bodywork)
    {
        //
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/Backend/ColorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Color;
use Illuminate\Http\Request;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors = Color::orderBy('name', 'asc')->paginate(config('constants.NUM_RECORDS_PER_PAGE'));
        
        return view('backend.color.index', compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.color.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Color $color)
    {
        $request->validate([
            'name' => 'required|min:3|max:20|unique:colors',
        ]);
        
        
        if ($color->create($request->all()))
        {
            return redirect()->route('colors.index')->with('success', 'Cor criada com sucesso!');
        }
        
        return redirect()->back()->with('error', 'Falha ao criar cor!')->withInput();
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    { 
        return view('backend.color.form', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color)
    {
        $request->validate([
            'name' => 'required|min:3|max:20|unique:colors',
        ]);
        
        
        if ($color->update($request->all()))
        {
            return redirect()->route('colors.index')->with('success', 'Cor atualizada com sucesso!');
        }
        
        return redirect()->back()->with('error', 'Falha ao atualizar cor!')->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color)
    {
        if ($color->delete()) {
            
            return redirect()->route('colors.index')->with('success', 'Cor removida com sucesso!');
        }
        
        return redirect()->back()->with('error', 'Falha ao remover cor!')->withInput();
    }
}

resources/views/backend/optional/form.blade.php
@extends('backend.template.app')

@section('main_title')
    {{ isset($optional) ? 'Editar opcional' : 'Novo opcional' }}
@endsection

@push('styles')
    <link rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
@endpush


@section('content')
    
    @include('backend.includes.errors')
    
    
    @if (isset($optional))
        {!! Form::model($optional, ['route' => ['optionals.update', $optional->id], 'method' => 'PUT']) !!}
    @else
        {!! Form::open(['route' => 'optionals.store']) !!}
    @endif
    
   
    <div class="row">
        <div class="form-group col-md-6">
            <label for="url">Grupo</label>
            {!! Form::select('group_id', $groups, !empty($optional->group_id) ? $optional->group_id : null, 
                ['class' => 'form-control selectpicker show-tick', 
                'placeholder' => 'Selecione um grupo...', 'data-live-search' => 'true']) !!}
        </div>
                
        <div class="form-group col-md-6">
            <label for="name">Nome</label>
            {!! Form::text('name', null, ['class' => 'form-control altura', 
                    'placeholder' => 'Informe o nome do opcional...']) !!}
        </div>     
    </div>
    
    <br/><br/>
    
    <div class="row">    
        <div class="text-right col-xs-12">
            <div class="hidden-xs">
                <a href="{{ route('optionals.index') }}" class="btn btn-warning"> 
                    <i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar a Listagem
                </a>
                <button type="submit" class="btn btn-primary"><i class="fa fa-refresh"></i> Salvar Dados</button>
            </div>
        </div>
    </div>
    
        
    {!! Form::close() !!}    

@endsection


@push('scripts')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function(){
        	$("select[name='group_id']").selectpicker({
                style: null    
            });
        });
        
     </script>
     
@endpush

resources/views/backend/optional/index.blade.php
@extends('backend.template.app')

@section('main_title')

    @if(isset($group))
        Opcionais do Grupo "{{ $group->name }}"
    @else
        Opcionais
    @endif
    
@endsection

@section('content')
    
    
    @include('backend.includes.alerts')
    
    
    <p class="text-right">
    
        @if (isset($group)) 
            <a href="{{ route('groups.index') }}" class="btn btn-warning">
                Voltar para a listagem de grupos
            </a>
        @endif
    
        <a href="{{ route('optionals.create') }}" class="btn btn-primary">
            <i class="fa fa-plus-circle"></i> Cadastrar Novo
        </a>
    </p>
    
    
    <table class="table table-striped table-bordered" id="tb1">
        <tr>
            <th>Nome</th>
            <th width="25%">Grupo</th>
            <th class="text-center" width="150px">
                <i class="fa fa-cog"></i>
            </th>
        </tr>
        
        @forelse($optionals as $optional)        
            <tr>
                <td> {{ $optional->name }}</td>
                <td> {{ $optional->group->name }}</td>
                <td class="text-center">
                
                    <a href="{{ route('optionals.edit', $optional->id) }}" class="btn btn-primary btn-sm" 
                        data-toggle="tooltip" title="editar">
                        <i class="fa fa-edit"></i>
                    </a>
                    
                    <button data-link="{{ route('optionals.destroy', $optional->id) }}" data-toggle="tooltip" 
                        data-resource="{{ $optional->name }}" class="btn btn-danger btn-sm btn-remover" 
                        title="remover">
                            <i class="fa fa-trash"></i> 
                    </button>
                </td>
            </tr>
        @empty
        
            <tr>
                <td colspan='3' style='text-align: center;'>Nenhum registro encontrado!</td>            
            </tr>
            
        @endforelse
    </table>
    
    
    <div class="row">
        <div class="col-md-12 text-center">
            {{ $optionals->links() }}
        </div>
    </div>
    
    @include('backend.includes.modal_delete', ['title' => 'opcional', 'text' => 'o opcional', 
       'route' => 'optionals.destroy'])
    
    
@endsection


@push('scripts')
    
    <!-- inclui o javascript necessário para exiber o modal para confirmação da exclusão  -->  
    <script type="text/javascript" src="{{ asset('assets/js/delete_actions.js') }}"></script>
     
@endpush